from zoneinfo import ZoneInfo

TIMEZONE = ZoneInfo("Europe/Madrid")
PASS_DAYS = 5
FUTURE_DAYS = 5

AIRPORT = [
    "PALMA DE MALLORCA",
    "GRAN CANARIA",
    "TENERIFE SUR",
    "TENERIFE NORTE-CIUDAD DE LA LAGUNA",
    "CÉSAR MANRIQUE-LANZAROTE",
    "FUERTEVENTURA",
    "MENORCA",
    "IBIZA",
    "MÁLAGA-COSTA DEL SOL",
    "SEVILLA",
    "JEREZ",
    "ALMERÍA",
    "JOSEP TARRADELLAS BARCELONA-EL PRAT",
    "GIRONA-COSTA BRAVA",
    "ALICANTE-ELCHE MIGUEL HERNÁNDEZ",
    "VALENCIA"
]