name: Run Flight Script

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  arrivals:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager beautifulsoup4

    - name: Run arrivals script
      run: |
        python __main__.py arrivals

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f arrivals_flights.json arrivals_status.json
        git commit -m 'Update flight data and script status for arrivals' || echo "No changes to commit"
    
    - name: Upload changes
      uses: actions/upload-artifact@v3
      with:
        name: arrivals-files
        path: |
          arrivals_flights.json
          arrivals_status.json

  departures:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager beautifulsoup4

    - name: Run departures script
      run: |
        python __main__.py departures

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -f departures_flights.json departures_status.json
        git commit -m 'Update flight data and script status for departures' || echo "No changes to commit"

    - name: Upload changes
      uses: actions/upload-artifact@v3
      with:
        name: departures-files
        path: |
          departures_flights.json
          departures_status.json

  push-changes:
    runs-on: ubuntu-latest
    needs: [arrivals, departures]

    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download arrivals files
      uses: actions/download-artifact@v3
      with:
        name: arrivals-files
        path: .

    - name: Download departures files
      uses: actions/download-artifact@v3
      with:
        name: departures-files
        path: .

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Verify changes
      run: git status

    - name: Commit and push all changes
      run: |
        git add -f arrivals_flights.json arrivals_status.json
        git add -f departures_flights.json departures_status.json
        git commit -m 'Final push: Updated flight data' || echo "No changes to commit"
        git pull --rebase
        git push
